# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 08:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paperstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], help_text='Mode of exam', max_length=2)),
                ('papernumber', models.PositiveSmallIntegerField(help_text='Number of paper for exam')),
                ('status', models.BooleanField(help_text='Activation status')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(help_text='Full Question name', max_length=500)),
                ('option1', models.CharField(help_text='A', max_length=50)),
                ('option2', models.CharField(help_text='B', max_length=50)),
                ('option3', models.CharField(help_text='C', max_length=50)),
                ('option4', models.CharField(help_text='D', max_length=50)),
                ('answer', models.CharField(help_text='Answer', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('papertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.Paperstype')),
            ],
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Add the technology type ..like python , jave and mysql etc..', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paperstype',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.TechType'),
        ),
    ]
