# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techtype',
            name='user',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
