# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0002_auto_20180103_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paperstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], help_text='Mode of exam', max_length=2)),
                ('papernumber', models.PositiveSmallIntegerField(help_text='Number of paper for exam')),
                ('status', models.BooleanField(help_text='Activation status')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.TechType')),
            ],
        ),
    ]
