# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0003_paperstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(help_text='Full Question name', max_length=500)),
                ('option1', models.CharField(help_text='A', max_length=50)),
                ('option2', models.CharField(help_text='B', max_length=50)),
                ('option3', models.CharField(help_text='C', max_length=50)),
                ('option4', models.CharField(help_text='D', max_length=50)),
                ('answer', models.CharField(help_text='Answer', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
