# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0004_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='papertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.Paperstype'),
        ),
    ]
