# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-11 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0007_auto_20180211_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperstype',
            name='test_duration',
        ),
    ]
