# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180330_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catagory',
        ),
    ]
