# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180405_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PY', 'Python'), ('ML', 'Machine Learning'), ('MLWPY', 'Machine Learning with Python')], default='ML', max_length=2),
        ),
    ]
