# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PY', 'Python'), ('ML', 'Machine Learning'), ('MLWPY', 'Machine Learning with Python'), ('FAQ', 'FAQ')], default='ML', max_length=2),
        ),
    ]
