# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
    ]
