# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCatagory',
        ),
    ]
