# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180330_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default='Null', upload_to='blogimg/'),
        ),
    ]
