# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], max_length=2)),
                ('current_status', models.CharField(choices=[('N', 'NotCompleted'), ('O', 'Onprocess'), ('C', 'Completed')], default='N', max_length=2)),
                ('upload_image', models.ImageField(default='null', upload_to='butrackimg/')),
                ('reference', models.CharField(default='Not Available', max_length=40)),
                ('final_status', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
