# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('comment', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
