# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackapp', '0002_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newuser',
        ),
    ]
