# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 08:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjectsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_photo', models.FileField(upload_to='stu_profiles/')),
                ('stu_status', models.FileField(upload_to='stu_status/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveSmallIntegerField(default=0)),
                ('total_question', models.PositiveSmallIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.Paperstype')),
            ],
        ),
        migrations.CreateModel(
            name='Testlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tst_name', models.CharField(default='coming soon', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Newuser',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'New user models',
                'verbose_name': 'New user model',
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='studentresults',
            name='stu_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stu_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
