# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifiedapp', '0003_testresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresults',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='testresults',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='testresults',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='testresults',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testresults',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='testresults',
            name='upload_image',
        ),
    ]
