# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifiedapp', '0004_auto_20180120_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testlist',
            old_name='assigned_to',
            new_name='testname',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='final_status',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='points',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='upload_image',
        ),
    ]
