# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifiedapp', '0005_auto_20180120_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taketest',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Testresults',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testlist',
            name='testname',
        ),
        migrations.AddField(
            model_name='testlist',
            name='tst_name',
            field=models.CharField(default=b'coming soon', max_length=50),
        ),
        migrations.DeleteModel(
            name='Taketest',
        ),
    ]
