# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 08:07
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('certifiedapp', '0006_auto_20180120_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'New user model',
                'indexes': [],
                'verbose_name_plural': 'New user models',
            },
            bases=('auth.user',),
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='testlist',
            name='tst_name',
            field=models.CharField(default='coming soon', max_length=50),
        ),
    ]
